plugins:
  compose_inline_components:
    client: true
    type: list
    default: ''
    choices:
      - topic-type
  compose_topic_types:
    client: true
    type: list
    default: 'general|content|question|rating|event'
    choices:
     - general
     - content
     - question
     - rating
     - event
  compose_restricted_topic_types:
    type: list
    default: 'petition|election'
    choices:
     - petition
     - election
  compose_general_min_trust:
    client: true
    default: 0
  compose_content_min_trust:
    client: true
    default: 1
  compose_question_min_trust:
    client: true
    default: 2
  compose_rating_min_trust:
    client: true
    default: 2
  compose_event_min_trust:
    client: true
    default: 2
  compose_peition_min_trust:
    client: true
    default: 3
  compose_election_min_trust:
    client: true
    default: 3
